// <auto-generated />
using System;
using FeeCollectorApplication.Service;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FeeCollectorApplication.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230210114136_seedDatabase")]
    partial class seedDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FeeCollectorApplication.ModelsSqlServer.Bill", b =>
                {
                    b.Property<int>("Bill_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Bill_id"));

                    b.Property<string>("license_plate_number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.HasKey("Bill_id");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("FeeCollectorApplication.ModelsSqlServer.BillHistory", b =>
                {
                    b.Property<int>("Bill_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Bill_id"));

                    b.Property<DateTime?>("Bill_datetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("license_plate_number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.HasKey("Bill_id");

                    b.ToTable("BillHistories");
                });

            modelBuilder.Entity("FeeCollectorApplication.ModelsSqlServer.Payment", b =>
                {
                    b.Property<int>("pay_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pay_id"));

                    b.Property<string>("license_plate_number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<float>("paid_price")
                        .HasColumnType("real");

                    b.Property<DateTime>("paid_time")
                        .HasColumnType("datetime2");

                    b.HasKey("pay_id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("FeeCollectorApplication.ModelsSqlServer.Vehicle", b =>
                {
                    b.Property<int>("Vehicle_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Vehicle_id"));

                    b.Property<string>("image_url")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("license_plate_number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("time_end")
                        .HasMaxLength(60)
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("time_start")
                        .HasMaxLength(20)
                        .HasColumnType("datetime2");

                    b.Property<string>("vehicle_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Vehicle_id");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("FeeCollectorApplication.ModelsSqlServer.VehicleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.Property<string>("vehicle_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VehicleTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
